name: Test with pytest

on: ['pull_request', 'push']

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        cache-dependency-glob: "pyproject.toml"
        enable-cache: true
        python-version: ${{ matrix.python-version }}
        version: 0.6.12
    - name: Install package and dependencies
      run: |
        uv sync --dev
    - name: Run tests
      run: |
        uv run pytest --cov-report xml:coverage.xml tests
    - name: Post coverage comment
      if: github.event_name == 'pull_request'
      uses: MishaKav/pytest-coverage-comment@v1
      with:
        pytest-xml-coverage-path: ./coverage.xml
        report-only-changed-files: true
