name: Test with pytest

on: ['pull_request', 'push']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Configure Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package and dependencies
      run: |
        python3 -m pip install --editable .
    - name: Install test dependencies
      run: |
        python3 -m pip install 'pytest>=8.0'
    - name: Run tests
      run: |
        python3 -m pytest tests
