name: Build Sphinx documentation

on:
  pull_request:
    paths:
      - "doc/**"
      - "pyproject.toml"
  push:
    paths:
      - "doc/**"
      - "pyproject.toml"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "pyproject.toml"
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: 0.6.12
      - name: Install package and dependencies
        run: |
          uv sync --group doc
      - name: Make gh-pages branch available
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: build/html
      - name: Build documentation
        run: |
          source .venv/bin/activate
          sphinx-build --doctree-dir build/doctrees --nitpicky doc build/html
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          pushd build/html
          git add --all .
          git commit -m "Built from ${GITHUB_REF}"
          git push --force
        continue-on-error: true
